variables:
  TWINE_USERNAME: $TWINE_USERNAME
  TWINE_PASSWORD: $TWINE_PASSWORD

include:
  template: Dependency-Scanning.gitlab-ci.yml

image: docker:latest

services:
  - docker:dind

registry:
  type: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY/oxr463/buildbot_tyrian_theme .
    - docker push $CI_REGISTRY/oxr463/buildbot_tyrian_theme

pypi:
  type: deploy
  before_script:
    - echo $CI_COMMIT_TAG > buildbot_tyrian_view/VERSION
    - |
         docker run -v $(pwd):/opt/buildbot_tyrian_theme \
                    $CI_REGISTRY/oxr463/buildbot_tyrian_theme \
                    python setup.py bdist_wheel sdist --formats gztar
  script:
    - docker run -e TWINE_USERNAME -e TWINE_PASSWORD -v $(pwd):/opt/buildbot_tyrian_theme $CI_REGISTRY/oxr463/buildbot_tyrian_theme twine upload dist/*
  only:
    - tags
