include:
  template: Dependency-Scanning.gitlab-ci.yml

image: python:alpine

install:
  type: test
  before_script:
    - python install -r requirements.txt
  script:
    - python setup.py install

pypi:
  type: deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  before_script:
    - pip install twine
    - python setup.py bdist_wheel sdist --formats gztar
  script:
    - twine upload dist/*
  only:
    - tags
